# 1. Rebuilds .agents/skills/INDEX.md from every skill's SKILL.md header.
# 2. Mirrors .agents/skills into .claude/skills so Claude Code shows them as slash commands.
# Edit skills in .agents/skills only, then run: pwsh scripts/sync-skills.ps1
# (Claude Code runs the .sh version automatically after file edits, see .claude/settings.json.)
$ErrorActionPreference = "Stop"
$checkOnly = $args -contains '-CheckOnly'
$root = Split-Path -Parent $PSScriptRoot
$source = Join-Path $root ".agents/skills"
$target = Join-Path $root ".claude/skills"
$index = Join-Path $source "INDEX.md"

function Get-SkillRow([string]$file, [string]$folder) {
  $lines = Get-Content -Path $file
  if ($lines.Count -eq 0 -or $lines[0] -ne "---") { return "| $folder | ``$folder`` | auto (by description) | - | (no header) |" }
  $name = $folder; $desc = ""; $steps = ""; $when = ""; $mode = ""
  for ($i = 1; $i -lt $lines.Count; $i++) {
    $line = $lines[$i]
    if ($line -eq "---") { break }
    if ($line -match '^name:\s*(.*)$') { $name = $Matches[1]; $mode = ""; continue }
    if ($line -match '^description:\s*(.*)$') {
      $value = $Matches[1]
      if ($value -in @(">", "|", ">-", "|-", "")) { $mode = "desc"; $desc = "" } else { $desc = $value; $mode = "" }
      continue
    }
    if ($line -match '^\s+sdd-steps:\s*(.*)$') { $steps = $Matches[1]; $mode = ""; continue }
    if ($line -match '^\s+sdd-when:\s*(.*)$') { $when = $Matches[1]; $mode = ""; continue }
    if ($mode -eq "desc" -and $line -match '^\s+(.*)$') { $desc = ($desc + " " + $Matches[1]).Trim(); continue }
    $mode = ""
  }
  if (-not $steps) { $steps = "auto (by description)" }
  if (-not $when) { $when = "-" }
  $desc = $desc -replace '\|', '/'
  if ($desc.Length -gt 140) { $desc = $desc.Substring(0, 137) + "..." }
  return "| $name | ``$folder`` | $steps | $when | $desc |"
}

$rows = @(
  "# Skills index", "",
  "Generated by scripts/sync-skills.* - do not edit. SDD steps read this, then",
  "scan the folders for anything newer (see .agents/rules/skill-discovery.md).", "",
  "| Skill | Folder | SDD steps | When | Description |",
  "| --- | --- | --- | --- | --- |"
)
$dirs = Get-ChildItem -Path $source -Directory | Where-Object { Test-Path (Join-Path $_.FullName "SKILL.md") }
foreach ($dir in $dirs) { $rows += Get-SkillRow (Join-Path $dir.FullName "SKILL.md") $dir.Name }
if ($checkOnly) {
  $expected = (($rows -join "`n").TrimEnd())
  $actual = if (Test-Path $index) { (Get-Content -Raw $index).Replace("`r`n", "`n").TrimEnd() } else { '' }
  if ($actual -ne $expected) { throw 'skill index drift detected' }
} else {
  Set-Content -Path $index -Value $rows -Encoding utf8
}
Write-Output "indexed $($dirs.Count) skills -> .agents/skills/INDEX.md"

New-Item -ItemType Directory -Force -Path $target | Out-Null
foreach ($dir in $dirs) {
  $dest = Join-Path $target $dir.Name
  if ($checkOnly) {
    $sourceFiles = @(Get-ChildItem -LiteralPath $dir.FullName -File -Recurse)
    foreach ($file in $sourceFiles) {
      $relative = $file.FullName.Substring($dir.FullName.Length).TrimStart('\','/')
      $mirrorFile = Join-Path (Join-Path $target $dir.Name) $relative
      if (-not (Test-Path $mirrorFile) -or (Get-FileHash $file.FullName).Hash -ne (Get-FileHash $mirrorFile).Hash) { throw "skill mirror drift: $($dir.Name)/$relative" }
    }
    continue
  }
  if (Test-Path $dest) { Remove-Item -Recurse -Force -Path $dest -Confirm:$false }
  Copy-Item -Recurse -Path $dir.FullName -Destination $dest
  Write-Output "synced $($dir.Name)"
}
