#!/usr/bin/env sh
# 1. Rebuilds .agents/skills/INDEX.md from every skill's SKILL.md header.
# 2. Mirrors .agents/skills into .claude/skills so Claude Code shows them as slash commands.
# Edit skills in .agents/skills only, then run: sh scripts/sync-skills.sh
# (Claude Code runs this automatically after file edits, see .claude/settings.json.)
set -eu
root="$(cd "$(dirname "$0")/.." && pwd)"
skills="$root/.agents/skills"
index="$skills/INDEX.md"

# Prints one table row from a SKILL.md header: name | steps | when | description
row() {
  awk -v folder="$2" '
    NR == 1 && $0 != "---" { exit }
    NR > 1 && $0 == "---" { done = 1 }
    done { next }
    /^name:/ { sub(/^name:[ ]*/, ""); name = $0; mode = ""; next }
    /^description:/ {
      sub(/^description:[ ]*/, "")
      if ($0 == ">" || $0 == "|" || $0 == ">-" || $0 == "|-" || $0 == "") { mode = "desc"; desc = "" } else { desc = $0; mode = "" }
      next
    }
    /^[ ]+sdd-steps:/ { sub(/^[ ]+sdd-steps:[ ]*/, ""); steps = $0; mode = ""; next }
    /^[ ]+sdd-when:/ { sub(/^[ ]+sdd-when:[ ]*/, ""); when = $0; mode = ""; next }
    mode == "desc" && /^[ ]+/ { line = $0; sub(/^[ ]+/, "", line); desc = desc (desc == "" ? "" : " ") line; next }
    { mode = "" }
    END {
      if (name == "") name = folder
      if (steps == "") steps = "auto (by description)"
      if (when == "") when = "-"
      gsub(/\|/, "/", desc)
      if (length(desc) > 140) desc = substr(desc, 1, 137) "..."
      printf "| %s | `%s` | %s | %s | %s |\n", name, folder, steps, when, desc
    }
  ' "$1"
}

{
  echo "# Skills index"
  echo
  echo "Generated by scripts/sync-skills.* - do not edit. SDD steps read this, then"
  echo "scan the folders for anything newer (see .agents/rules/skill-discovery.md)."
  echo
  echo "| Skill | Folder | SDD steps | When | Description |"
  echo "| --- | --- | --- | --- | --- |"
  for dir in "$skills"/*/; do
    name="$(basename "$dir")"
    [ -f "$dir/SKILL.md" ] || continue
    row "$dir/SKILL.md" "$name"
  done
} > "$index"
echo "indexed $(grep -c '^| [^-S]' "$index" || true) skills -> .agents/skills/INDEX.md"

mkdir -p "$root/.claude/skills"
for dir in "$skills"/*/; do
  name="$(basename "$dir")"
  rm -rf "$root/.claude/skills/$name"
  cp -R "$dir" "$root/.claude/skills/$name"
  echo "synced $name"
done
